server:
  port: 9999

spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      routes:
      - id: files
        uri: lb://FILE-SERVICE
        predicates:
          - Path=/movies/**
      - id: authorization
        uri: lb://AUTHORIZATION
        predicates:
          - Path=/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/