version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strongPassword
    networks:
      - local_network

  mysql-db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - local_network
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldb:/var/lib/mysql/

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql-db
    ports:
      - "9411:9411"

volumes:
  mysqldb:
    driver: local

networks:
  local_network:
    driver: bridge